require ("prototypes.GNFT-5d-loaders")
require ("prototypes.GNFT-circuit-network")
require ("prototypes.GNFT-landfill")
require ("prototypes.GNFT-circuit-updates")
require ("prototypes.GNFT-belt-sorter")
require ("prototypes.GNFT-nixie-tubes")
require ("prototypes.GNFT-science")