--if mods["omniscience"] then
--    if settings.startup["omniscience-rocket-modified-by-omni"]then
--        if mods.["omniwater"]then
--            if settings.startup["water-levels"].value == 20 then
-- put on hold for now...
